title: Mariana Santana Amaral
description: Personal site + projects
theme: minima

defaults:
  - scope:
      path: ""
    values:
      lang: "pt"
  - scope:
      path: "en"
    values:
      lang: "en"

header_pages:
  - about.md
  - projects.md
  - en/about.md